### ISSUE TITLE
Add GitHub logo to the navbar

### ISSUE THREAD

**Issue by KonstantinLang** [PSIAIMS/CAMIS#118]
I was on your page today for the first time and I highly appreciate the work you do!

I was looking for a link to the GitHub repo and had to search a bit. It would be great to add the GitHub icon to the navbar. See below for some example code.

```
website:
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/PSIAIMS/CAMIS/
          - text: Report a Bug
            url:  https://github.com/PSIAIMS/CAMIS/issues/
```
